---
  - name: Create users
    user:
      name: "{{ item }}"
      password: "{{ lookup('password', '/tmp/.' + item + '_password chars=ascii_letters length=6 encrypt=sha512_crypt') }}"
      append: yes
      state: present
      createhome: yes
    with_items: "{{ users }}"

  - name: Copy password
    copy:
      content: "{{ lookup('password', '/tmp/.' + item + '_password chars=ascii_letters length=6') }}"
      dest: "/home/{{ item }}/.password"
      owner: "{{ item }}"
      mode: '0400'
    with_items: "{{ users }}"
...