---
  dependency:
    name: galaxy
  driver:
    name: docker
  platforms:
    - name: ansible-role-users
      image: centos:7
  provisioner:
    name: ansible
  verifier:
    name: ansible
  lint: |
    set -e
    ansible-lint .
...